trigger:
  - main

pool:
  name: Default

parameters:
  - name: runApply
    displayName: "Run Terraform Apply?"
    type: boolean
    default: false

variables:
  - group: SEC_MS
  - name: TF_VERSION
    value: "1.7.5"

stages:
  - stage: Dev
    displayName: "Terraform Plan (Dev)"
    jobs:
      - job: TerraformPlanDev
        displayName: "Run Terraform Plan for Dev"
        steps:

          - task: Bash@3
            displayName: "Terraform Init"
            inputs:
              targetType: "inline"
              workingDirectory: terraform/build_agent
              script: |
                ls
                pwd
                terraform init -backend-config=backend.config
            env:
              ARM_ACCESS_KEY: $(ARMACCESSKEY)
              ARM_CLIENT_ID: $(ARMCLIENTID)
              ARM_CLIENT_SECRET: $(ARMCLIENTSECRET)
              ARM_SUBSCRIPTION_ID: $(ARMSUBSCRIPTIONID)
              ARM_TENANT_ID: $(ARMTENANTID)

          - task: Bash@3
            displayName: "Terraform Plan"
            inputs:
              targetType: "inline"
              workingDirectory: terraform/build_agent
              script: |
                terraform plan -var-file="parameters/common.tfvars" -out=common-tfplan

          # - task: Bash@3
          #   displayName: "Terraform Apply (Dev)"
          #   condition: and(succeeded(), eq('${{ parameters.runApply }}', true))
          #   inputs:
          #     targetType: "inline"
          #     workingDirectory: infra/core-infra
          #     script: |
          #       terraform apply dev-tfplan
          #   env:
          #     ARM_ACCESS_KEY: $(ARMACCESSKEY)
          #     ARM_CLIENT_ID: $(ARMCLIENTID)
          #     ARM_CLIENT_SECRET: $(ARMCLIENTSECRET)
          #     ARM_SUBSCRIPTION_ID: $(ARMSUBSCRIPTIONID)
          #     ARM_TENANT_ID: $(ARMTENANTID)
